---
title: "Constructing Custom Examples"
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 6
vignette: >
  %\VignetteIndexEntry{Constructing Custom Examples
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Introduction

Intro.

# Section 1

The `@caption` tag should be used to provide a brief
description of the example. The `@info` tag should be used to provide a more
detailed description of the example. The `@code` tag should be used to
provide the code for the example. See `rdx_roclet()` for more details. The
examples should be separated in two parts:

- The first part are examples which demonstrate the functionality of the
  function. The first example shows the default behavior. Then examples for
  each optional argument follow. The data in these examples is as concise as
  possible and may not be ADaM compliant, e.g., `STUDYID` is not included or
  `AVISITN` is present without `AVISIT`.
      
  These examples should answer questions like "what does this function?" or
  "how does this argument work?".
  
- The second part are examples which demonstrate which ADaM variables or
  parameters could be derived with the function. The code could be copied to
  an ADaM script and be used without or with small modifications.
      
  Each example includes a "specs-like" description.
      
  These examples should answer questions like "how can this
  variable/parameter be derived".

# Section 2

Text
