name: Dependency Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-test:
    strategy:
      fail-fast: false
      matrix:
        test-strategy: ["min_cohort", "min_isolated", "release", "max"]
    uses: insightsengineering/r.pkg.template/.github/workflows/verdepcheck.yaml@main
    name: Dependency Test - ${{ matrix.test-strategy }} 🔢
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.PHARMAVERSE_BOT }}
    with:
      strategy: ${{ matrix.test-strategy }}
      additional-env-vars: |
        PKG_SYSREQS_DRY_RUN=true

